services:
  - type: web
    name: oct-retina-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MODEL_URL
        value: https://drive.google.com/file/d/1aHZ2YE_Z67KpxhUc4rqjpf5Y2LDYQCVs/view?usp=sharing
